// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export interface Artifact {
    "kind": OutputMode;
    "path": string;
    "available": boolean;
}

export interface AudioFile {
    "path": string;
    "name": string;
    "durationSeconds": number;
    "sizeBytes": number;
    "format": string;
}

export enum AudioFormat {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AudioMP3 = "mp3",
    AudioM4A = "m4a",
    AudioOpus = "opus",
};

export interface AudioOptions {
    "format": AudioFormat;
    "quality": AudioQuality;
}

export enum AudioQuality {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AudioEconomy = "economy",
    AudioStandard = "standard",
    AudioHigh = "high",
};

export interface Format {
    "id": string;
    "extension": string;
    "videoCodec": string;
    "audioCodec": string;
    "width": number;
    "height": number;
    "bitrateKbps": number;
    "hasVideo": boolean;
    "hasAudio": boolean;
}

export interface Job {
    "id": JobID;
    "kind": JobKind;
    "source": Source;
    "inputPath"?: string;
    "media"?: Media | null;
    "mode": OutputMode;
    "audio": AudioOptions;
    "video": VideoQuality;
    "destination": string;
    "status": JobStatus;
    "progress": JobProgress;
    "artifacts"?: Artifact[] | null;
    "failure"?: JobError | null;
    "retryOf"?: JobID;
    "createdAt": string;
    "updatedAt": string;
    "startedAt"?: string | null;
    "finishedAt"?: string | null;
}

export interface JobError {
    "code": string;
    "message": string;
    "details"?: string;
}

export type JobID = string;

export enum JobKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    JobDownload = "download",
    JobLocalConversion = "local_conversion",
    JobAudioTrim = "audio_trim",
};

export enum JobPhase {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PhasePreparing = "preparing_dependencies",
    PhaseAnalyzing = "analyzing",
    PhaseQueued = "queued",
    PhaseDownloading = "downloading",
    PhaseMerging = "merging",
    PhaseExtracting = "extracting_audio",
    PhaseTranscoding = "transcoding",
    PhaseFinalizing = "finalizing",
};

export interface JobProgress {
    "phase": JobPhase;
    "fraction"?: number | null;
    "completedBytes"?: number;
    "totalBytes"?: number;
    "speedBytesPerSecond"?: number;
    "etaSeconds"?: number;
}

export enum JobStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    JobPending = "pending",
    JobAnalyzing = "analyzing",
    JobReady = "ready",
    JobDownloading = "downloading",
    JobProcessing = "processing",
    JobCompleted = "completed",
    JobFailed = "failed",
    JobCancelled = "cancelled",
};

export interface Media {
    "id": string;
    "title": string;
    "webpageURL": string;
    "thumbnailURL": string;
    "duration": time$0.Duration;
    "sizeBytes": number;
    "sizeEstimated": boolean;
    "drm": boolean;
    "formats": Format[] | null;
}

export enum OutputMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OutputVideo = "video",
    OutputAudio = "audio",
    OutputBoth = "both",
};

export interface Source {
    "url": string;
    "pageURL"?: string;
    "headers"?: { [_ in string]?: string } | null;
}

/**
 * TrimRequest removes seconds from either edge, never from an absolute end timestamp.
 */
export interface TrimRequest {
    "path": string;
    "startSeconds": number;
    "endSeconds": number;
}

export interface VideoQuality {
    "maxHeight": number;
}
