// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

export interface AudioPreview {
    "id": string;
    "source": core$0.AudioFile;
    "startSeconds": number;
    "endSeconds": number;
    "durationSeconds": number;
}

export interface SaveAudioRequest {
    "previewID": string;
    "overwrite": boolean;
}

export interface SavedAudio {
    "path": string;
    "overwritten": boolean;
}
