// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface SaveAudioRequest {
    "previewID": string;
    "overwrite": boolean;
}

export interface SavedAudio {
    "path": string;
    "overwritten": boolean;
}
