// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as core$0 from "../../../../PrudensMefron/govideo/internal/core/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as deps$0 from "../../../../PrudensMefron/govideo/internal/deps/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "dependency:updated": deps$0.Status;
            "files:dropped": string[] | null;
            "job:updated": core$0.Job;
        }
    }
}
