<script setup lang="ts">
import {computed,onBeforeUnmount,onMounted,ref} from 'vue'
import {Events} from '@wailsio/runtime'
import * as api from '../bindings/github.com/PrudensMefron/govideo/desktopservice'
import {AudioFormat,AudioQuality,Media as CoreMedia,OutputMode} from '../bindings/github.com/PrudensMefron/govideo/internal/core/models'
import type {Status as UpdateStatus} from '../bindings/github.com/PrudensMefron/govideo/internal/desktop/update/models'
type Media=CoreMedia
type Job={id:string;kind:string;inputPath?:string;media?:Media;mode:string;status:string;progress:{phase:string;fraction?:number;speedBytesPerSecond?:number};artifacts?:{path:string;available:boolean}[];failure?:{message:string};createdAt:string}
type Settings={videoDirectory:string;musicDirectory:string;conversionDirectory:string;theme:string};type Dep={name:string;state:string;version?:string;path?:string;error?:string;license?:string}
const page=ref<'home'|'activity'>('home'),mode=ref<'download'|'convert'>('download'),url=ref(''),busy=ref(false),error=ref(''),media=ref<Media|null>(null),jobs=ref<Job[]>([]),deps=ref<Dep[]>([]),files=ref<string[]>([]),settings=ref<Settings>({videoDirectory:'',musicDirectory:'',conversionDirectory:'',theme:'system'}),update=ref<UpdateStatus|null>(null),checkingUpdate=ref(false),updateError=ref(''),output=ref(OutputMode.OutputVideo),height=ref(0),audioFormat=ref(AudioFormat.AudioMP3),audioQuality=ref(AudioQuality.AudioStandard),mediaDialog=ref<HTMLDialogElement>(),settingsDialog=ref<HTMLDialogElement>()
const active=(j:Job)=>['pending','analyzing','ready','downloading','processing'].includes(j.status)
const qualities=computed(()=>[0,...new Set((media.value?.formats||[]).filter(f=>f.hasVideo&&f.height>0&&f.height<=2160).map(f=>f.height))].sort((a,b)=>b-a))
const phases:Record<string,string>={preparing_dependencies:'Preparando dependências',queued:'Na fila',analyzing:'Analisando',downloading:'Baixando',merging:'Combinando faixas',extracting_audio:'Extraindo áudio',transcoding:'Convertendo',finalizing:'Finalizando'}
const phase=(j:Job)=>phases[j.progress?.phase]||j.status, title=(j:Job)=>j.media?.title||j.inputPath?.split(/[\\/]/).pop()||'Mídia'
const bytes=(n=0)=>n?`${(n/(n>1e9?1e9:1e6)).toFixed(1)} ${n>1e9?'GB':'MB'}`:'—';const time=(ns=0)=>{const s=Math.round(ns/1e9);return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
async function refresh(){try{jobs.value=await api.ListJobs(0,50) as Job[];deps.value=await api.ListDependencies() as Dep[];settings.value=await api.GetSettings() as Settings;update.value=await api.GetUpdateStatus() as UpdateStatus}catch{}}
async function refreshUpdate(){try{update.value=await api.GetUpdateStatus() as UpdateStatus}catch{}}
async function checkUpdates(){checkingUpdate.value=true;updateError.value='';try{update.value=await api.CheckForUpdates() as UpdateStatus}catch(e){updateError.value=String(e);await refreshUpdate()}finally{checkingUpdate.value=false}}
async function analyze(){error.value='';if(!url.value.trim()){error.value='Cole um endereço válido para analisar.';return}busy.value=true;try{media.value=await api.AnalyzeURL({url:url.value}) as Media;if(media.value.drm){error.value='Esta mídia possui proteção DRM e não pode ser baixada.';return}mediaDialog.value?.showModal()}catch(e){error.value=String(e)}finally{busy.value=false}}
async function download(){if(!media.value)return;busy.value=true;try{await api.StartDownload({url:url.value,media:media.value,mode:output.value,maxHeight:height.value,audioFormat:audioFormat.value,audioQuality:audioQuality.value,destination:output.value==='audio'?settings.value.musicDirectory:settings.value.videoDirectory});mediaDialog.value?.close();page.value='activity';await refresh()}catch(e){error.value=String(e)}finally{busy.value=false}}
async function choose(){try{files.value=(await api.SelectInputVideos())||[]}catch(e){error.value=String(e)}}
async function convert(){busy.value=true;try{await api.StartLocalConversions({paths:files.value,audioFormat:audioFormat.value,audioQuality:audioQuality.value,destination:settings.value.conversionDirectory});files.value=[];page.value='activity';await refresh()}catch(e){error.value=String(e)}finally{busy.value=false}}
async function folder(k:keyof Settings){const p=await api.SelectDestination(String(k));if(p)settings.value={...settings.value,[k]:p}}
async function save(){settings.value=await api.UpdateSettings(settings.value);applyTheme();settingsDialog.value?.close()}
function applyTheme(){document.documentElement.dataset.theme=settings.value.theme==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'govideo-dark':'govideo-light'):`govideo-${settings.value.theme}`}
let off:(()=>void)[]=[];onMounted(async()=>{await refresh();applyTheme();off=[Events.On('job:updated',e=>{const j=e.data as Job,i=jobs.value.findIndex(x=>x.id===j.id);i<0?jobs.value.unshift(j):jobs.value[i]=j}),Events.On('dependency:updated',e=>{const d=e.data as Dep,i=deps.value.findIndex(x=>x.name===d.name);i<0?deps.value.push(d):deps.value[i]=d}),Events.On('update:updated',e=>{update.value=e.data as UpdateStatus}),Events.On('wails:updater:update-available',()=>refreshUpdate()),Events.On('wails:updater:no-update',()=>refreshUpdate()),Events.On('wails:updater:error',()=>refreshUpdate()),Events.On('files:dropped',e=>{files.value=[...new Set([...files.value,...e.data as string[]])];mode.value='convert'})]});onBeforeUnmount(()=>off.forEach(f=>f()))
</script>
<template>
<div class="shell"><header><button class="brand" @click="page='home'"><i>▶</i><b>GoVideo</b></button><nav aria-label="Principal"><button :class="{on:page==='home'}" @click="page='home'">⌂ Início</button><button :class="{on:page==='activity'}" @click="page='activity'">☷ Atividades <em v-if="jobs.some(active)">{{jobs.filter(active).length}}</em></button></nav><button class="gear" aria-label="Configurações" @click="settingsDialog?.showModal()">⚙</button></header>
<main v-if="page==='home'"><div class="segments" role="tablist" aria-label="Tipo de operação"><button role="tab" :aria-selected="mode==='download'" @click="mode='download'">↗ Baixar da internet</button><button role="tab" :aria-selected="mode==='convert'" @click="mode='convert'">♫ Converter vídeo em música</button></div>
<section v-if="mode==='download'" class="workspace"><h1>Cole o link do vídeo aqui</h1><p>Baixe vídeos ou áudios dos principais sites.</p><form class="url" novalidate @submit.prevent="analyze"><span>↗</span><label class="sr" for="url">Endereço da mídia</label><input id="url" v-model="url" type="url" placeholder="https://"><button class="primary" :disabled="busy">{{busy?'Analisando…':'Analisar'}}</button></form><p v-if="error" class="error" role="alert">{{error}}</p><div class="empty"><i>↗</i><b>Nenhum link analisado ainda</b><span>Cole um link acima para começar</span><small v-if="deps.find(d=>d.name==='yt-dlp')?.state==='installing'">Preparando ferramenta de análise…</small></div></section>
<section v-else class="workspace" data-file-drop-target><h1>Transforme vídeos em música</h1><p>Selecione ou arraste vários arquivos. Cada vídeo vira um job independente.</p><div class="drop" data-file-drop-target><i>＋</i><b>Arraste vídeos para cá</b><span>MP4, MKV, WebM, MOV, AVI ou M4V</span><button class="secondary" @click="choose">Selecionar vídeos</button></div><ul class="files"><li v-for="f in files" :key="f"><span>▣</span><b>{{f.split(/[\\/]/).pop()}}</b><button :aria-label="`Remover ${f}`" @click="files=files.filter(x=>x!==f)">×</button></li></ul><div class="options"><label>Formato<select v-model="audioFormat"><option>mp3</option><option>m4a</option><option>opus</option></select></label><label>Qualidade<select v-model="audioQuality"><option value="economy">Econômica</option><option value="standard">Padrão</option><option value="high">Alta</option></select></label><button class="primary" :disabled="!files.length||busy" @click="convert">Converter {{files.length||''}}</button></div></section></main>
<main v-else class="activities"><div class="title"><div><h1>Atividades</h1><p>Acompanhe a fila, o processamento e seus arquivos.</p></div><span>{{jobs.length}} jobs</span></div><div v-if="!jobs.length" class="empty"><i>☷</i><b>Nenhuma atividade ainda</b><span>Seus downloads e conversões aparecerão aqui.</span></div><ul v-else class="jobs"><li v-for="j in jobs" :key="j.id"><i class="jobicon">{{j.kind==='download'?'↓':'♫'}}</i><div class="info"><b>{{title(j)}}</b><span>{{j.kind==='download'?'Download online':'Conversão local'}} · {{phase(j)}}</span><small v-if="j.failure" class="error">{{j.failure.message}}</small></div><div class="progress"><div><span :class="j.status">{{phase(j)}}</span><span>{{j.progress?.fraction!=null?Math.round(j.progress.fraction*100)+'%':'—'}}</span></div><progress :value="j.progress?.fraction" max="1"></progress><small v-if="j.progress?.speedBytesPerSecond">{{bytes(j.progress.speedBytesPerSecond)}}/s</small></div><div class="actions"><button v-if="active(j)" @click="api.CancelJob(j.id)">Cancelar</button><button v-if="['failed','cancelled'].includes(j.status)" @click="api.RetryJob(j.id)">Tentar novamente</button><button v-for="a in j.artifacts?.filter(x=>x.available)" :key="a.path" @click="api.OpenArtifactLocation(a.path)">Abrir pasta</button></div></li></ul></main></div>
<dialog ref="mediaDialog"><div class="dialoghead"><h2>Mídia analisada</h2><button aria-label="Fechar" @click="mediaDialog?.close()">×</button></div><div v-if="media" class="summary"><img v-if="media.thumbnailURL" :src="media.thumbnailURL" alt=""><div><h3>{{media.title}}</h3><p>{{time(media.duration)}} · {{media.sizeEstimated?'Tamanho estimado: ':''}}{{bytes(media.sizeBytes)}}</p></div></div><fieldset><legend>O que você quer baixar?</legend><div class="choices"><label v-for="m in [{v:'video',l:'▣ Vídeo'},{v:'audio',l:'♫ Música'},{v:'both',l:'▣ ♫ Vídeo e Música'}]" :key="m.v"><input v-model="output" type="radio" :value="m.v"><span>{{m.l}}</span></label></div></fieldset><div class="formgrid"><label v-if="output!=='audio'">Resolução<select v-model="height"><option v-for="q in qualities" :key="q" :value="q">{{q?`${q}p`:'Melhor disponível'}}</option></select></label><label v-if="output!=='video'">Formato<select v-model="audioFormat"><option>mp3</option><option>m4a</option><option>opus</option></select></label><label v-if="output!=='video'">Qualidade<select v-model="audioQuality"><option value="economy">Econômica</option><option value="standard">Padrão</option><option value="high">Alta</option></select></label></div><div class="dialogactions"><button class="secondary" @click="mediaDialog?.close()">Cancelar</button><button class="primary" @click="download">Iniciar download</button></div></dialog>
<dialog ref="settingsDialog"><div class="dialoghead"><h2>Configurações</h2><button aria-label="Fechar" @click="settingsDialog?.close()">×</button></div><section class="settings"><h3>Ferramentas</h3><div v-for="d in deps" :key="d.name" class="dep"><div><b>{{d.name}}</b><span>{{d.version||d.path||'Não disponível'}}</span><small>{{d.license}}</small></div><span :class="d.state">{{d.state}}</span><button v-if="['failed','invalid','missing'].includes(d.state)" @click="api.RetryDependency(d.name)">Tentar novamente</button></div><h3>Atualizações</h3><div v-if="update" class="update"><div><b>GoVideo {{update.currentVersion}}</b><span v-if="!update.enabled">Atualizações desativadas nesta build de desenvolvimento.</span><span v-else-if="update.availableVersion">Versão {{update.availableVersion}} disponível.</span><span v-else>Canal estável · GitHub Releases</span><small>{{update.repository}}</small><small v-if="updateError||update.error" class="error">{{updateError||update.error}}</small></div><button :disabled="!update.enabled||checkingUpdate" @click="checkUpdates">{{checkingUpdate?'Verificando…':update.availableVersion?'Baixar atualização':'Verificar atualizações'}}</button></div><h3>Pastas padrão</h3><label v-for="k in (['videoDirectory','musicDirectory','conversionDirectory'] as const)" :key="k">{{k==='videoDirectory'?'Vídeos':k==='musicDirectory'?'Músicas':'Conversões'}}<div class="path"><input v-model="settings[k]"><button @click="folder(k)">Selecionar</button></div></label><label>Tema<select v-model="settings.theme"><option value="system">Acompanhar o sistema</option><option value="light">Claro</option><option value="dark">Escuro</option></select></label></section><div class="dialogactions"><button class="secondary" @click="settingsDialog?.close()">Cancelar</button><button class="primary" @click="save">Salvar</button></div></dialog>
</template>
