// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as updater$0 from "../../../../../wailsapp/wails/v3/pkg/updater/models.js";

export interface Status {
    "enabled": boolean;
    "state": updater$0.State;
    "currentVersion": string;
    "availableVersion"?: string;
    "repository": string;
    "error"?: string;
}
