// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "./internal/core/models.js";

export interface AnalyzeRequest {
    "url": string;
}

export interface ConversionDTO {
    "paths": string[] | null;
    "audioFormat": core$0.AudioFormat;
    "audioQuality": core$0.AudioQuality;
    "destination": string;
}

export interface DownloadDTO {
    "url": string;
    "media": core$0.Media;
    "mode": core$0.OutputMode;
    "maxHeight": number;
    "audioFormat": core$0.AudioFormat;
    "audioQuality": core$0.AudioQuality;
    "destination": string;
}

export interface Settings {
    "videoDirectory": string;
    "musicDirectory": string;
    "conversionDirectory": string;
    "theme": string;
}
