// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * State is the high-level lifecycle phase the Updater is currently in.
 */
export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateUnconfigured = "unconfigured",
    StateIdle = "idle",
    StateChecking = "checking",
    StateUpToDate = "up-to-date",
    StateAvailable = "available",
    StateDownloading = "downloading",
    StateVerifying = "verifying",
    StateInstalling = "installing",
    StateReady = "ready",
    StateError = "error",
};
